name: Build Mesen

on: [push]

env:
  # I'm not a fan of the telemetry as-is, but this also suppresses some lines in the build log.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  # This removes even more spurious lines.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  appimage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy libsdl2-dev libfuse2 # The compilers are already installed on GitHub's runners.
      
      - name: Install PupNet Deploy
        run: dotnet tool install -g KuiperZone.PupNet

      - name: Build Mesen (AppImage)
        run: |
          pupnet Mesen --new desktop
          pupnet Mesen --new meta
          pupnet -y --runtime linux-x64 --kind appimage -o Mesen.AppImage
        env:
          PUBLISHFLAGS: -r $(MESENPLATFORM) --no-self-contained false -p:PublishSingleFile=true -p:PublishReadyToRun=true
      - name: Upload Mesen (AppImage)
        uses: actions/upload-artifact@v3
        with:
          name: Mesen (Linux x64 - AppImage)
          path: Deploy/OUT/Mesen.AppImage
