name: Build Mesen

on: [push]

env:
  # I'm not a fan of the telemetry as-is, but this also suppresses some lines in the build log.
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  # This removes even more spurious lines.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  linux:
    strategy:
      matrix:
        compiler: [gcc] #, clang]
        os: [ubuntu-22.04] #, ubuntu-20.04]
        exclude:
          # This currently fails to build.
          - os: ubuntu-20.04
            compiler: gcc
        include:
          - compiler: gcc
            use_gcc: "USE_GCC=true"
          #- compiler: clang
          #  use_gcc: ""
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Install dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy libsdl2-dev # The compilers are already installed on GitHub's runners.
      
      - name: Install PupNet Deploy
        run: dotnet tool install -g KuiperZone.PupNet
        
      - name: Execute unit tests
        run: dotnet test --nologo

      # stderr is not detected as a TTY, so diagnostics are by default printed without colours;
      # forcing colours makes the log a little nicer to read.
      #- name: Build Mesen (Standalone executeable)
      #  run: |
      #    make -j$(nproc) -O ${{ matrix.use_gcc }} LTO=true STATICLINK=true SYSTEM_LIBEVDEV=false
      #- name: Upload Mesen (Standalone executeable)
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Mesen (Linux - ${{ matrix.os }} - ${{ matrix.compiler }})
      #    path: bin/linux-x64/Release/linux-x64/publish/Mesen
      - name: Build Mesen (AppImage)
        run: |
          pupnet Mesen --new all --verbose
          pupnet -y --runtime linux-x64 --kind appimage -o Mesen.AppImage
      #- name: Upload Mesen (AppImage)
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: Mesen (Linux x64 - AppImage)
          # TO-ADD: path
  
